spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    topic:
      helloworld: helloworld.t

logging:
  level:
      - ".=warn"
      - "com.memorynotfound=debug"
      - "org.springframework=warn"